# AuditFox - Open Source Audit Logging Solution
# Copyright (C) 2025 Danzopen by Daniel Barbosa

name: Build and Tests
on:
  push:
    branches: [ "main", "feature/*", "fix/*" ]
  pull_request:
    branches: [ "main", "feature/*", "fix/*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auditfox/src

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.5

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install golangci-lint
      run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

    - name: Run golangci-lint
      run: golangci-lint run ./...

    - name: Run tests
      run: go test -race -vet=off ./...
